version: "3.9"
services:
  postgresql:
    container_name: db
    image: postgres:latest
    restart: always
    networks:
      - application
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: josepsoares
      POSTGRES_PASSWORD: nuodV4!Be@27EL
      POSTGRES_DB: iberia_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  go-fiber-api:
    container_name: iberiapi
    image: iberiapi-arch:latest
    restart: always
    networks:
      - application
    ports:
      - 8080:8080
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - db
    command: ./iberiapi-arch

networks:
  application:

volumes:
  postgres-data:
    driver: local
