version: "3.9"
services:
  fiber-application:
    restart: always
    image: docker-oh-portugal-api-arch:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - 8080:8080
    networks:
      - application
    depends_on:
      - postgresql
    command: ./docker-oh-portugal-api-arch

  postgresql:
    restart: always

    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - application

networks:
  application:

volumes:
  postgres-data:
    driver: local
